Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/BlockLength:
  Max: 40
Layout/LineLength:
  Max: 130
Metrics/PerceivedComplexity:
  Max: 8
Layout/EndOfLine:
  Enabled: false

AllCops:
  Exclude:
    - 'lesson_1/**/*'
    - 'lesson_2/**/*'
    - 'lesson_3/**/*'
    - 'lesson_4/**/*'
    - 'lesson_5/**/*'
    - 'lesson_6/**/*'
    - 'lesson_7/**/*'

